"""
Constants and enumerations for Unified OSS Framework.

Provides centralized constant definitions used throughout the framework.
"""

# Vendor identifiers
VENDOR_ERICSSON = "ERICSSON"
VENDOR_HUAWEI = "HUAWEI"
VENDOR_NOKIA = "NOKIA"
VENDOR_ZTE = "ZTE"
VENDOR_SAMSUNG = "SAMSUNG"
VENDOR_CISCO = "CISCO"

# Severity levels
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_MAJOR = "MAJOR"
SEVERITY_MINOR = "MINOR"
SEVERITY_WARNING = "WARNING"
SEVERITY_INDETERMINATE = "INDETERMINATE"
SEVERITY_CLEARED = "CLEARED"

# Alarm states
ALARM_STATE_ACTIVE = "ACTIVE"
ALARM_STATE_ACKNOWLEDGED = "ACKNOWLEDGED"
ALARM_STATE_CLEARED = "CLEARED"
ALARM_STATE_RESOLVING = "RESOLVING"
ALARM_STATE_SUPPRESSED = "SUPPRESSED"

# Configuration states
CONFIG_STATE_DRAFT = "DRAFT"
CONFIG_STATE_PENDING_APPROVAL = "PENDING_APPROVAL"
CONFIG_STATE_APPROVED = "APPROVED"
CONFIG_STATE_STAGED = "STAGED"
CONFIG_STATE_DEPLOYED = "DEPLOYED"
CONFIG_STATE_FAILED = "FAILED"
CONFIG_STATE_ROLLED_BACK = "ROLLED_BACK"

# NETCONF datastores
DATASTORE_RUNNING = "running"
DATASTORE_CANDIDATE = "candidate"
DATASTORE_STARTUP = "startup"

# Default ports
NETCONF_DEFAULT_PORT = 830
SSH_DEFAULT_PORT = 22
SNMP_DEFAULT_PORT = 161
HTTP_DEFAULT_PORT = 80
HTTPS_DEFAULT_PORT = 443

# Timeouts (seconds)
DEFAULT_CONNECTION_TIMEOUT = 30
DEFAULT_OPERATION_TIMEOUT = 60
DEFAULT_COMMIT_TIMEOUT = 600

# Kafka topics
TOPIC_RAW_ALARMS_ERICSSON = "raw-alarms-ericsson"
TOPIC_RAW_ALARMS_HUAWEI = "raw-alarms-huawei"
TOPIC_RAW_PM_ERICSSON = "raw-pm-ericsson"
TOPIC_RAW_PM_HUAWEI = "raw-pm-huawei"
TOPIC_RAW_CONFIG_ERICSSON = "raw-config-ericsson"
TOPIC_RAW_CONFIG_HUAWEI = "raw-config-huawei"
TOPIC_UNIFIED_ALARMS = "unified-alarms"
TOPIC_UNIFIED_PM = "unified-pm"
TOPIC_UNIFIED_CONFIG = "unified-config"
TOPIC_DEAD_LETTER = "dead-letter-queue"

# Performance thresholds
MAX_ALARM_AGE_HOURS = 8760  # 1 year
MAX_ALARM_HISTORY_DAYS = 90
MAX_CONFIG_HISTORY_VERSIONS = 50
CACHE_TTL_SECONDS = 3600

# Regular expressions
UUID_PATTERN = r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
RESOURCE_PATH_PATTERN = r"/network/[A-Za-z]+/[A-Za-z]+/[A-Za-z0-9_\-]+(/[A-Za-z0-9_\-]+)*"

# Severity mappings for Ericsson
ERICSSON_SEVERITY_MAP = {
    "critical": SEVERITY_CRITICAL,
    "major": SEVERITY_MAJOR,
    "minor": SEVERITY_MINOR,
    "warning": SEVERITY_WARNING,
    "indeterminate": SEVERITY_INDETERMINATE,
    "cleared": SEVERITY_CLEARED,
}

# Severity mappings for Huawei (integer-based)
HUAWEI_SEVERITY_MAP = {
    1: SEVERITY_CRITICAL,
    2: SEVERITY_MAJOR,
    3: SEVERITY_MINOR,
    4: SEVERITY_WARNING,
    0: SEVERITY_INDETERMINATE,
}

# CIM namespace
CIM_NAMESPACE = "urn:cim:v1"
CIM_VERSION = "1.0.0"

# FCAPS domains
FCAPS_FAULT = "fault"
FCAPS_CONFIGURATION = "configuration"
FCAPS_ACCOUNTING = "accounting"
FCAPS_PERFORMANCE = "performance"
FCAPS_SECURITY = "security"

# Network element types
NE_TYPE_ENODEB = "ENodeB"
NE_TYPE_GNODEB = "GNodeB"
NE_TYPE_MME = "MME"
NE_TYPE_SGW = "SGW"
NE_TYPE_PGW = "PGW"
NE_TYPE_HSS = "HSS"
NE_TYPE_AMF = "AMF"
NE_TYPE_SMF = "SMF"
NE_TYPE_UPF = "UPF"
NE_TYPE_UDM = "UDM"
NE_TYPE_NRF = "NRF"
NE_TYPE_IMS = "IMS"
NE_TYPE_TAS = "TAS"
NE_TYPE_DRA = "DRA"
NE_TYPE_DEA = "DEA"
NE_TYPE_STP = "STP"

# Configuration operation types
OPERATION_CREATE = "CREATE"
OPERATION_MODIFY = "MODIFY"
OPERATION_DELETE = "DELETE"
OPERATION_APPLY = "APPLY"
OPERATION_ROLLBACK = "ROLLBACK"
OPERATION_COMMIT = "COMMIT"

# Notification channels
CHANNEL_EMAIL = "EMAIL"
CHANNEL_SMS = "SMS"
CHANNEL_SNMP_TRAP = "SNMP_TRAP"
CHANNEL_SYSLOG = "SYSLOG"
CHANNEL_WEBHOOK = "WEBHOOK"
CHANNEL_WEBSOCKET = "WEBSOCKET"
CHANNEL_KAFKA = "KAFKA"

# Audit actions
AUDIT_ACTION_CREATE = "CREATE"
AUDIT_ACTION_READ = "READ"
AUDIT_ACTION_UPDATE = "UPDATE"
AUDIT_ACTION_DELETE = "DELETE"
AUDIT_ACTION_DEPLOY = "DEPLOY"
AUDIT_ACTION_ROLLBACK = "ROLLBACK"
AUDIT_ACTION_APPROVE = "APPROVE"
AUDIT_ACTION_REJECT = "REJECT"

# User roles
ROLE_ADMIN = "ADMIN"
ROLE_OPERATOR = "OPERATOR"
ROLE_ENGINEER = "ENGINEER"
ROLE_VIEWER = "VIEWER"
ROLE_APPROVER = "APPROVER"
ROLE_AUDITOR = "AUDITOR"

# Zero Trust levels
ZERO_TRUST_LEVEL_LOW = 0.0
ZERO_TRUST_LEVEL_MEDIUM = 0.5
ZERO_TRUST_LEVEL_HIGH = 1.0
ANOMALY_THRESHOLD = 0.7

# Database table names
TABLE_ALARMS = "alarms"
TABLE_ALARM_HISTORY = "alarm_history"
TABLE_METRICS = "metrics"
TABLE_CONFIGURATIONS = "configurations"
TABLE_CONFIG_VERSIONS = "config_versions"
TABLE_SECURITY_EVENTS = "security_events"
TABLE_AUDIT_LOG = "audit_log"
TABLE_NETWORK_ELEMENTS = "network_elements"
TABLE_TOPOLOGY = "topology"

# Metric types
METRIC_TYPE_COUNTER = "COUNTER"
METRIC_TYPE_GAUGE = "GAUGE"
METRIC_TYPE_HISTOGRAM = "HISTOGRAM"
METRIC_TYPE_SUMMARY = "SUMMARY"

# KPI categories
KPI_CATEGORY_AVAILABILITY = "AVAILABILITY"
KPI_CATEGORY_QUALITY = "QUALITY"
KPI_CATEGORY_CAPACITY = "CAPACITY"
KPI_CATEGORY_RETAINABILITY = "RETAINABILITY"
KPI_CATEGORY_MOBILITY = "MOBILITY"
KPI_CATEGORY_THROUGHPUT = "THROUGHPUT"
